config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  Rails.application.routes.draw do
    resources :todos do
      resources :tasks, only: %i[new create edit update destroy index show]
    end
  end

  root to: 'todos#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

# Module containing helper methods for the Application.
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
# frozen_string_literal: true

# Module containing helper methods for Task model.
class Task < ApplicationRecord
  belongs_to :todo

  validates_presence_of :description
end

app/models/todo.rb
# frozen_string_literal: true

# Module containing helper methods for Todo model.
class Todo < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates_presence_of :description
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# This device create, update, show, destroy a Task into Todo List
class TasksController < ApplicationController
  before_action :set_todo
  before_action :set_task, only: %i[update show destroy edit]

  def index
    @tasks = @todo.tasks
  end

  def new
    @task = @todo.tasks.new
  end

  def create
    @task = @todo.tasks.new(task_params)
    if @task.save
      flash[:notice] = 'Task criada com sucesso.'
      redirect_to todo_tasks_path(@todo)
    else
      flash.now[:alert] = @task.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @task.update(task_params)
      flash[:notice] = 'Task atualizada com sucesso.'
      redirect_to todo_task_path(@todo, @task)
    else
      flash.now[:alert] = @task.errors.full_messages.to_sentence
      render :edit
    end
  end

  def show; end

  def destroy
    @task.destroy
    flash[:notice] = 'Task deletada com sucesso.'
    redirect_to todo_tasks_path(@todo)
  end

  def edit; end

  private

  def set_todo
    @todo = Todo.find(params[:todo_id])
  end

  def task_params
    params.require(:task).permit(:completed, :description)
  end

  def set_task
    @task = @todo.tasks.find(params[:id])
  end
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

# This device create, update, show, destroy a Todo List
class TodosController < ApplicationController
  before_action :set_todo, only: %i[update show destroy edit]

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = 'Todo criado com sucesso.'
      redirect_to todos_path
    else
      flash.now[:alert] = @todo.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @todo.update(todo_params)
      flash[:notice] = 'Todo atualizado com sucesso.'
      redirect_to todos_path
    else
      flash.now[:alert] = @todo.errors.full_messages.to_sentence
      render :edit
    end
  end

  def show; end

  def destroy
    puts "Destroy action called for todo ID: #{params[:id]}"
    @todo.destroy!
    flash[:notice] = 'Todo deletado com sucesso.'
    redirect_to todos_path
  end

  def edit; end

  private

  def todo_params
    params.require(:todo).permit(:completed, :description, :parent_todo_id)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Module containing helper methods for the application views.
module ApplicationHelper
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

# Module containing helper methods for Lists module.
module ListsHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

# Module containing helper methods for Tasks module.
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag  "turbo" ,type: "module" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: [@todo, @task] do |form| %> 
  <div> 
    <h3>Task Name:
      <%= form.text_field :description, class:"text-box" %></h3>
  </h3>
  <h3>
      <%= form.label :completed, "Completed" %>
      <%= form.check_box :completed, class:"custom-checkbox" %>
  </h3>
  <%= form.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task for <%= @todo.description %></h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', todo_tasks_path, class:'action' %>

app/views/tasks/index.html.erb
<h1>All Tasks for Todo <%= @todo.description %></h1>

<div>
  <%= link_to 'Add New Task', new_todo_task_path, class:"newList" %>
</div>
<table>
  <thead>
    <tr>
      <th style="margin-right:50px">Description</th>
      <th>Completed</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td class="description"><%= task.description %></td>
        <td class="completed"><%= task.completed ? 'Yes' : 'No' %></td>
        <td class="actions">
          <%= link_to 'Show', todo_task_path(task.todo, task), class:"action" %>
          <%= link_to 'Edit', edit_todo_task_path(task.todo, task), class:"action" %>
          <%= link_to 'Delete', todo_task_path(task.todo, task), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"action"%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', todos_path, class:'action' %>

app/views/tasks/new.html.erb
<h1>Creating task for <%= @todo.description %></h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', todo_tasks_path, class:'action' %>

app/views/tasks/show.html.erb
<h1>Task Details</h1>

<div class="show">

    <tr>
      <td class="description">
        <h3>Description:
        <%= @task.description %>
        </h3>
      </td>
      <hr>
      <td class="completed">
        <h3>Completed:
          <%= @task.completed ? 'Yes' : 'No' %>
        </h3>
      </td>
    <td>

  </div>
<%= link_to 'Back', todo_tasks_path, class:'action' %>

app/views/todos/_form.html.erb
<%= form_with model: @todo do |form| %>
  <div> 
    <h3>Task Name:
      <%= form.text_field :description, class:"text-box" %></h3>
  </h3>
  <h3>
      <%= form.label :completed, "Completed" %>
      <%= form.check_box :completed, class:"custom-checkbox" %>
  </h3>
  <%= form.submit %>
<% end %>

app/views/todos/destroy.html.erb
<%= form_with url: todo_path(todo), method: :destroy, local: true do %>
    <%= submit_tag "Delete" %>
  <% end %>

app/views/todos/edit.html.erb
<h1>Editing</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path, class:'action' %>

app/views/todos/index.html.erb
<h1>Todo</h1>

<div class="teste2">
  <%= link_to 'Add New Todo', new_todo_path, class:"newList" %>
</div>
<table>
  <thead>
    <tr>
      <th style="margin-right:50px">Description</th>
      <th>Completed</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td class="description"><%= todo.description %></td>
        <td class="completed"><%= todo.completed ? 'Yes' : 'No' %></td>
        <td class="actions">
          <%= link_to 'Show', todo_path(todo), class:"action_todo" %>
          <%= link_to 'Edit', edit_todo_path(todo), class:"action_todo" %>
          <%= link_to 'Delete', todo_path(todo), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"action_todo"%>
          <%= link_to 'View Tasks', todo_tasks_path(todo), class:"action_todo" %>
          <%= link_to 'Add Task', new_todo_task_path(todo), class:"action_todo" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/todos/new.html.erb
<h1>Creating</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path, class:'action' %>

app/views/todos/show.html.erb
<h1>Todo Details</h1>

<div class="show">

    <tr>
      <td class="description">
        <h3>Description:
        <%= @todo.description %>
        </h3>
      </td>
      <hr>
      <td class="completed">
        <h3>Completed:
          <%= @todo.completed ? 'Yes' : 'No' %>
        </h3>
      </td>
    <td>

  </div>
<%= link_to 'Back', todos_path, class:'action' %>